/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#dbdad7",
        "surface-container-low": "#f4f3f1",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb94c",
        "surface-container-highest": "#e3e2e0",
        "outline": "#72796e",
        "error-container": "#ffdad6",
        "surface-tint": "#3b6934",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2f312f",
        "primary-fixed": "#bcf0ae",
        "secondary-fixed-dim": "#b0cfad",
        "secondary-fixed": "#ccebc7",
        "on-tertiary-fixed-variant": "#624000",
        "secondary": "#4a6549",
        "on-surface-variant": "#42493e",
        "surface-container-high": "#e9e8e5",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#506b4f",
        "tertiary-fixed": "#ffddb2",
        "on-primary-fixed": "#002201",
        "inverse-on-surface": "#f2f1ee",
        "on-secondary-fixed": "#07200b",
        "surface-container": "#efeeeb",
        "surface-bright": "#faf9f6",
        "tertiary": "#503300",
        "on-tertiary-container": "#fbb546",
        "error": "#ba1a1a",
        "on-primary-container": "#9dd090",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "outline-variant": "#c2c9bb",
        "on-surface": "#1a1c1a",
        "secondary-container": "#ccebc7",
        "surface": "#faf9f6",
        "tertiary-container": "#6e4800",
        "background": "#faf9f6",
        "on-secondary-fixed-variant": "#334d33",
        "on-tertiary-fixed": "#291800",
        "inverse-primary": "#a1d494",
        "surface-variant": "#e3e2e0",
        "primary-container": "#2d5a27",
        "on-background": "#1a1c1a",
        "primary-fixed-dim": "#a1d494",
        "on-primary-fixed-variant": "#23501e",
        "on-secondary": "#ffffff",
        "primary": "#154212",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Be Vietnam Pro", "sans-serif"],
        label: ["Be Vietnam Pro", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};